### ISSUE TITLE
Dis(v) under "Highest Ranking Modpacks" not centered on mobile 

### ISSUE THREAD

**Issue by Mark-a-obrien** [CalaMariGold/MMC-Reviews#10]
Hello, 

In mobile view the "Highest Ranking Modpacks" cards are not centered. (See screenshot below)

Looks like the unordered list (ul) is centered but the div(s) with class `wp-block-stackable-columns stk-block-columns stk--hide-desktop stk--hide-tablet stk-block stk-ea08266 stk-block-background homepage-post-blocks` isn't.

![not centered div](https://github.com/CalaMariGold/MMC-Reviews/assets/84234570/94474e4f-8b93-406f-8440-b30a710cc5dd)
![ul centered](https://github.com/CalaMariGold/MMC-Reviews/assets/84234570/0981244d-1ede-4525-ae34-f1aabeec45d4)

![Capture](https://github.com/CalaMariGold/MMC-Reviews/assets/84234570/e97ced3e-0464-4b7b-a283-76eae21ca793)

**Comment by CalaMariGold** [comment]
Thank you for reporting this! Been trying to fix this one for awhile now, not sure why it's giving me so much trouble but I'll keep working on it.

**Comment by CalaMariGold** [comment]
Fixed... was so simple I feel stupid 🙃

**Comment by Mark-a-obrien** [comment]
Nice one. Looks good to me
