### ISSUE TITLE
Text in cards under "Highest Ranking Mods" is being cut off. 

### ISSUE THREAD

**Issue by Mark-a-obrien** [CalaMariGold/MMC-Reviews#11]
Hello,

The text Text in cards under "Highest Ranking Mods" is being cut off.  (Screenshots below)

The card seems to be getting its height from the div with classes `wp-block-stackable-columns stk-block-columns stk--hide-desktop stk--hide-tablet stk-block stk-7789dfd stk-block-background homepage-post-blocks`.

but the div with classes `stk-row stk-inner-blocks has-text-align-center-mobile stk-block-content stk-content-align stk-7789dfd-column` looks like its aligned correctly.

![text being cut](https://github.com/CalaMariGold/MMC-Reviews/assets/84234570/758b567a-11cf-4647-b282-4ba49271f733)
![div goes beyond text cut off](https://github.com/CalaMariGold/MMC-Reviews/assets/84234570/f6c190e8-a329-4412-aa8c-623be296ad8f)

**Comment by CalaMariGold** [comment]
Thanks for catching this! Somehow I forgot to properly configure some values for mobile. Should be fixed now.

**Comment by Mark-a-obrien** [comment]
> Thanks for catching this! Somehow I forgot to properly configure some values for mobile. Should be fixed now.

Nice. Looks good.
