### ISSUE TITLE
"Highest Ranking" sort sometimes excludes unrated mods/packs

### ISSUE THREAD

**Issue by asanetargoss** [CalaMariGold/MMC-Reviews#2]
It seems to be random. Sometimes the pages are excluded, and sometimes they are not.

Seems to be happening to me with the "Food" tag for example, but other tags are also affected.

**Comment by CalaMariGold** [comment]
Highest Ranking sorting will only show mods/modpacks that have at least 1 review. So for example there is only one mod with "Food" that is rated currently (Lycanites Mobs), so only that mod will show.

Let me know if there is any other confusion I can clear up or if I'm misunderstanding.
![image](https://user-images.githubusercontent.com/57605926/235316775-3767e83f-e917-4a35-8303-c5818cd2df12.png)

**Comment by asanetargoss** [comment]
See also the "Exploration" tag. Behavior appears to be inconsistent there.

**Comment by CalaMariGold** [comment]
I see what you mean now! Thanks for pointing this out. I've fixed it
