### ISSUE TITLE
Paragraphs on the website lack separation

### ISSUE THREAD

**Issue by Foreck1** [CalaMariGold/MMC-Reviews#3]
Some paragraphs are not separated on the actual reviews on the website, whereas you can visibly see them on embeds. 
![image](https://user-images.githubusercontent.com/47757429/235318453-25cc6c7b-4022-40b8-92d6-c10e1994b6e6.png)
![image](https://user-images.githubusercontent.com/47757429/235318471-26866972-b7d6-47af-826f-b5c400d59e79.png)

**Comment by CalaMariGold** [comment]
Forgot to close this but this has been fixed a little bit ago.
