### ISSUE TITLE
Spoiler text can break text wrapping

### ISSUE THREAD

**Issue by coolbot100s** [CalaMariGold/MMC-Reviews#4]
When a large block of text is spoilered, it no longer wraps at the border of of the review when viewing the review's card after clicking read more.
https://mmcreviews.com/all/modpacks/universio/

![image](https://user-images.githubusercontent.com/76798835/235517022-12f4c4fc-0311-40f6-ba10-6af42f1362b5.png)
![image](https://user-images.githubusercontent.com/76798835/235517726-1086f985-8bb2-4ea5-b0d3-f32e7c9a093e.png)

**Comment by CalaMariGold** [comment]
Good catch! Thank you for the report. Simple fix, should be all good now
