### ISSUE TITLE
Invalid SSL Certificate

### ISSUE THREAD

**Issue by asanetargoss** [CalaMariGold/MMC-Reviews#5]
Just refreshed the page and am getting an error from Cloudflare saying the SSL Certificate is invalid. Refreshing the page, I see this error from Firefox:

```
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for mmcreviews.com. The certificate is only valid for the following names: *.pressable.com, pressable.com
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by CalaMariGold** [comment]
Hi, sorry about that. The server was being migrated for better performance. Everything should be back up now. Clear your browser cache if it's still occurring
