### ISSUE TITLE
Search button on Android?

### ISSUE THREAD

**Issue by ZonkoTheGreat** [CalaMariGold/MMC-Reviews#6]
Dunno if this is a bug or I need to wait for results, but clicking "mods" or "modpacks" option doesnt do anything on android.  Was there meant to be a search button?

![Screenshot_20230525_075831_Chrome](https://github.com/CalaMariGold/MMC-Reviews/assets/41207710/508e956a-c5d4-45d5-80d8-5a19f75d5447)

**Comment by CalaMariGold** [comment]
When using any of the filters, it takes a moment for the results to update, but they should update automatically. The filters will stay greyed out until the results are finished loading.

Feel free to reopen if I'm misunderstanding or something actually isn't working.
