### ISSUE TITLE
Minecraft versions should probably not be sorted by popularity

### ISSUE THREAD

**Issue by MattiDragon** [CalaMariGold/MMC-Reviews#7]
On the current search page the minecraft versions are sorted by popularity. I think it would make a lot more sense to put them in their natural order instead. Currently it's somewhat annoying to pick a version as you don't know where in the dropdown to look for it.

**Comment by CalaMariGold** [comment]
Thank you for pointing this out! I agree it makes more sense to order them by version. This change is currently live.
