### ISSUE TITLE
Submission form Tag suggestions / autofill

### ISSUE THREAD

**Issue by coolbot100s** [CalaMariGold/MMC-Reviews#8]
It would be  nice if the project tags field in the submission form could auto suggest and complete from the existing tags on the site.
It would make the end user experience much faster and more efficient, improve the accuracy of tags submitted as all the options can be laid out to be seen plainly, prevent the creation of redundant or mispelt tags, and save site administration some time fixing these easy to make mistakes.

![image](https://github.com/CalaMariGold/MMC-Reviews/assets/76798835/26b20292-9fef-4729-bd71-2d8653b3c1a6)

**Comment by CalaMariGold** [comment]
I absolutely agree! This would be amazing. I will try everything I can to implement this.

**Comment by CalaMariGold** [comment]
Implemented!
