### ISSUE TITLE
Option to submit a first review.

### ISSUE THREAD

**Issue by coolbot100s** [CalaMariGold/MMC-Reviews#9]
I think an optional field(s) for submitting your review as a part of the submission form could be a huge help for the user experience, allowing them to write their review for a new mod/pack at the same time as submitting it. 
This review could then be added to the mod/pack's page once (if) it is created. Not only does this streamline and save time for the end user, but it should hopefully significantly decrease the amount of content with no reviews.

**Comment by CalaMariGold** [comment]
Thank you for the suggestion, but I don't think this is possible unfortunately. I also don't want people submitting reviews for a project that hasn't been approved yet.
